# Generated by Django 3.0.4 on 2020-04-17 11:25

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_date', models.DateField(verbose_name='发布日期')),
            ],
            options={
                'verbose_name': '评分对象',
                'verbose_name_plural': '评分对象',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=20, verbose_name='单位名称')),
                ('unit_cate', models.CharField(choices=[('建制营', '建制营'), ('建制连队', '建制连队'), ('非建制单位', '非建制单位'), ('机关股室', '机关股室'), ('首长领导', '首长领导')], max_length=20, verbose_name='单位类别')),
                ('scorer_cate', models.CharField(choices=[('基层', '基层'), ('机关', '机关'), ('领导', '领导')], max_length=10, verbose_name='评分身份')),
                ('member_list', models.CharField(default=' ', max_length=300, verbose_name='单位自查评分成员')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '单位',
                'verbose_name_plural': '单位列表',
            },
        ),
        migrations.CreateModel(
            name='Score_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scorer', models.CharField(choices=[('基层', '基层'), ('机关', '机关'), ('领导', '领导')], max_length=10, verbose_name='打分单位')),
                ('major_term', models.CharField(choices=[('铁一般信仰', '铁一般信仰'), ('铁一般信念', '铁一般信念'), ('铁一般纪律', '铁一般纪律'), ('铁一般担当', '铁一般担当'), ('机关专项检查', '机关专项检查'), ('机关综合检查', '机关综合检查'), ('机关自查', '机关自查'), ('基层测评', '基层测评'), ('领导打分', '领导打分'), ('其它', '其它')], max_length=100, verbose_name='所属主项')),
                ('detail_cate', models.CharField(choices=[('每周', '每周'), ('每月', '每月'), ('每季度', '每季度'), ('半年', '半年'), ('一年', '一年'), ('即时性工作(扣分)', '即时性工作(扣分)')], max_length=20, verbose_name='细则类型')),
                ('detail_name', models.CharField(max_length=100, verbose_name='细则名称')),
                ('max_score', models.IntegerField(default=0, verbose_name='最大分值')),
                ('description', models.CharField(default=' ', max_length=500, verbose_name='细则描述')),
                ('notes', models.CharField(default=' ', max_length=500, verbose_name='备注')),
                ('unit_score', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, verbose_name='分数')),
                ('release_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_items', to='strive2api.Score', verbose_name='发布对象')),
            ],
            options={
                'verbose_name': '评分细则',
                'verbose_name_plural': '评分细则',
            },
        ),
        migrations.AddField(
            model_name='score',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='strive2api.Unit', verbose_name='单位名称'),
        ),
    ]
