# Generated by Django 3.0.4 on 2020-04-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strive2api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='member_list',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='单位自查评分成员'),
        ),
    ]
