# Generated by Django 3.0.4 on 2020-04-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strive2api', '0005_auto_20200422_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score_item',
            name='notes',
            field=models.CharField(blank=True, max_length=500, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='scorer_major_cate',
            field=models.CharField(choices=[('建制营', '建制营'), ('基层', '基层'), ('机关', '机关'), ('领导', '领导')], max_length=20, verbose_name='评分身份'),
        ),
    ]
