# Generated by Django 3.0.4 on 2020-05-06 21:20

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strive2api', '0007_auto_20200422_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season_ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('season', models.IntegerField(verbose_name='季度')),
                ('total_basis', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, verbose_name='分数')),
                ('total_instit', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, verbose_name='分数')),
                ('total_leader', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, verbose_name='分数')),
                ('total_other', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, verbose_name='分数')),
                ('total_belief_basis', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, verbose_name='分数')),
                ('total_faith_basis', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, verbose_name='分数')),
                ('total_discipline_basis', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, verbose_name='分数')),
                ('total_responsible_basis', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, verbose_name='分数')),
                ('total_belief_instit', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, verbose_name='分数')),
                ('total_faith_instit', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, verbose_name='分数')),
                ('total_discipline_instit', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, verbose_name='分数')),
                ('total_responsible_instit', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, verbose_name='分数')),
                ('total_special', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, verbose_name='分数')),
                ('total_comprenhensive', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, verbose_name='分数')),
                ('total_institself', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, verbose_name='分数')),
                ('total_basisevaluate', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, verbose_name='分数')),
                ('total_leaderevaluate', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, verbose_name='分数')),
                ('total_score', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, verbose_name='分数')),
                ('season_rank', models.IntegerField(verbose_name='季度排名')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_rankings', to='strive2api.Unit', verbose_name='季度得分')),
            ],
            options={
                'verbose_name': '季度得分',
                'verbose_name_plural': '季度得分',
            },
        ),
    ]
