# Generated by Django 3.0.4 on 2020-05-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strive2api', '0008_season_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season_ranking',
            name='season_rank',
            field=models.IntegerField(default=0, verbose_name='季度排名'),
        ),
    ]
