# Generated by Django 3.0.4 on 2020-05-09 17:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strive2api', '0012_auto_20200509_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score_item',
            name='unit_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='分数'),
        ),
        migrations.AlterField(
            model_name='season_ranking',
            name='total_basis',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='基层'),
        ),
        migrations.AlterField(
            model_name='season_ranking',
            name='total_basisevaluate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='基层测评'),
        ),
        migrations.AlterField(
            model_name='season_ranking',
            name='total_belief_basis',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='基层自评-铁一般信仰'),
        ),
        migrations.AlterField(
            model_name='season_ranking',
            name='total_belief_instit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='机关测评-铁一般信仰'),
        ),
        migrations.AlterField(
            model_name='season_ranking',
            name='total_comprenhensive',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='机关综合检查'),
        ),
        migrations.AlterField(
            model_name='season_ranking',
            name='total_discipline_basis',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='基层自评-铁一般纪律'),
        ),
        migrations.AlterField(
            model_name='season_ranking',
            name='total_discipline_instit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='机关测评-铁一般纪律'),
        ),
        migrations.AlterField(
            model_name='season_ranking',
            name='total_faith_basis',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='基层自评-铁一般信念'),
        ),
        migrations.AlterField(
            model_name='season_ranking',
            name='total_faith_instit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='机关测评-铁一般信念'),
        ),
        migrations.AlterField(
            model_name='season_ranking',
            name='total_instit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='机关'),
        ),
        migrations.AlterField(
            model_name='season_ranking',
            name='total_institself',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='机关自查'),
        ),
        migrations.AlterField(
            model_name='season_ranking',
            name='total_leader',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='领导'),
        ),
        migrations.AlterField(
            model_name='season_ranking',
            name='total_leaderevaluate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='领导打分'),
        ),
        migrations.AlterField(
            model_name='season_ranking',
            name='total_other',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='其它'),
        ),
        migrations.AlterField(
            model_name='season_ranking',
            name='total_responsible_basis',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='基层自评-铁一般担当'),
        ),
        migrations.AlterField(
            model_name='season_ranking',
            name='total_responsible_instit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='机关测评-铁一般担当'),
        ),
        migrations.AlterField(
            model_name='season_ranking',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='季度总分'),
        ),
        migrations.AlterField(
            model_name='season_ranking',
            name='total_special',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='机关专项检查'),
        ),
    ]
